version: '3'
services:
  db:
    image: postgres:alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - ./pg_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379

  